version: '3'
services:
  redis:
    image: redis
    container_name: gobarber_redis
    command: '--appendonly yes'
    ports:
      - 6380:6379
  mongodb:
    image: mongo
    container_name: gobarber_mongo
    ports:
      - 27017:27017
  postgres:
    image: postgres
    container_name: gobarber_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5433:5432
